FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache git curl \
	&& curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

COPY go.mod go.sum ./

RUN go mod download


EXPOSE 8000

CMD ["air", "-c", ".air.toml", "-d"]
