root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -buildvcs=false -o ./tmp/book-service ./services/book-service/cmd"
bin = "./tmp/book-service"
full_bin = ""
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", ".git"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
log = "air.book.log"

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
