FROM golang:1.24-alpine


WORKDIR /app

RUN apk add --no-cache git curl \
	&& curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

RUN curl -fsSL -o /usr/local/bin/dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64 \
	&& chmod +x /usr/local/bin/dbmate

COPY go.mod go.sum ./

RUN go mod download


EXPOSE 8080 50051

CMD ["air", "-c", ".air.book.toml", "-d"]
